title: Helen Triages Food
description: What to cook, not how to cook
url: ""
baseurl: "/food"

show_unrewritten: false

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
  drafts:
    output: true
    permalink: /drafts/:path/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
      rewritten: false
  - scope:
      path: ""
      type: drafts
    values:
      layout: recipe
      rewritten: false

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
